FROM node:18-alpine AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm install pocketbase
RUN npm run build


FROM node:18-alpine AS prod

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=build /app/package.json .

RUN npm install --omit=dev

EXPOSE 3000

CMD ["node", "build/index.js"]