version: "3.8"

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    environment:
      VITE_POCKETBASE_URL: "http://pocketbase:8090"

  pocketbase:
    image: elestio/pocketbase:latest
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
    restart: unless-stopped
    user: root  # ✅ Runs PocketBase as root
    entrypoint: [ "sh", "-c", "
      chmod -R 777 /pb_data;
      if [ ! -f /pb_data/admin_created ]; then
        /usr/local/bin/pocketbase superuser create nilltill05@gmail.com nani171717 && touch /pb_data/admin_created ;
      fi;
      /usr/local/bin/pocketbase serve --http 0.0.0.0:8090;
    " ]

  setup:
    build:
      context: .
      dockerfile: dockerfile.setup
    container_name: pocketbase-setup
    depends_on:
      - pocketbase
    restart: on-failure

volumes:
  pocketbase_data:
